finance_keywords = [
            'financial', 'statement', 'balance sheet', 'income statement', 'cash flow statement',
            'revenue', 'profit', 'loss', 'earnings', 'expense', 'cost', 'margin', 'profitability',
            'assets', 'liabilities', 'equity', 'debt', 'leverage', 'liquidity', 'working capital',
            'investment', 'portfolio', 'asset allocation', 'diversification', 'return on investment',
            'ROI', 'risk', 'volatility', 'beta', 'alpha', 'sharpe ratio', 'capital market', 'bull market',
            'bear market', 'stock', 'bond', 'derivative', 'option', 'hedging', 'futures', 'valuation',
            'PE ratio', 'EPS', 'dividend', 'yield', 'fundamental analysis', 'technical analysis',
            'financial modeling', 'forecasting', 'cash flow forecasting', 'market trend', 'market analysis',
            'economic indicators', 'interest rate', 'inflation', 'Federal Reserve', 'central bank',
            'monetary policy', 'exchange rate', 'forex', 'currency', 'hedge fund', 'mutual fund',
            'investment strategy', 'asset management', 'financial planning', 'tax', 'taxation',
            'tax planning', 'credit', 'debit', 'credit score', 'bankruptcy', 'merger', 'acquisition',
            'initial public offering', 'IPO', 'divestiture', 'capital budgeting', 'working capital management',
            'financial risk', 'credit risk', 'market risk', 'operational risk', 'liquidity risk',
            'credit rating', 'credit analysis', 'financial regulation', 'compliance', 'financial institution',
            'insurance', 'pension', 'retirement planning', 'savings', 'investor', 'trading', 'market order',
            'limit order', 'stop order', 'bullish', 'bearish', 'technical indicator', 'moving average',
            'candlestick', 'volatility index', 'private equity', 'venture capital', 'fixed income',
            'corporate finance', 'capital structure', 'WACC', 'cost of capital', 'financial engineering',
            'financial instrument', 'securities', 'equity market', 'bond market', 'money market',
            'capital market', 'derivatives market', 'financial crisis', 'economic downturn', 'recession',
            'depression', 'stimulus package', 'fiscal policy', 'monetary stimulus', 'quantitative easing',
            'financial planning', 'retirement savings', '401(k)', 'IRA', 'wealth management',
            'financial advisor', 'investment advisor', 'tax advisor', 'financial literacy', 'personal finance', 'stable',
            'growth', 'portfolio management', 'asset class', 'capital allocation', 'risk management', 'capital gain',
            'dividend yield', 'cost of living', 'liquidity ratio', 'ROA', 'ROE', 'solvency', 'financial leverage',
            'interest coverage ratio', 'dividend payout ratio', 'P/B', 'P/E', 'market capitalization', 'book value',
            'leverage ratio', 'arbitrage', 'bull market rally', 'short selling', 'blue-chip stocks', 'DRIP',
            'efficient market hypothesis', 'insider trading', 'M&A', 'underwriting', 'ABS', 'MBS', 'CDO', 'CDS',
            'securitization', 'financial derivatives', 'options trading', 'volatility skew', 'technical analysis indicators',
            'fundamental analysis ratios', 'behavioral finance', 'CAR', 'derivatives trading', 'tax-efficient investing',
            'expense ratio', 'systematic risk', 'unsystematic risk', 'capital gain tax', 'cash and carry trade',
            'earnings yield', 'value investing', 'growth investing', 'SIP', 'asset turnover ratio', 'capital budgeting techniques',
            'yield curve', 'real estate investment', 'SRI', 'cryptocurrency', 'DeFi', 'P2P'
]